# Generated by Django 5.2.1 on 2025-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='location',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donation_photos/'),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
