# Generated by Django 5.2.1 on 2025-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0002_remove_fooddonation_location_fooddonation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
