# Generated by Django 5.2.1 on 2025-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0003_fooddonation_collected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='collected_at',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='photo',
        ),
    ]
