# Generated by Django 5.2.1 on 2025-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0004_remove_fooddonation_collected_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needylocation',
            old_name='name',
            new_name='sender_name',
        ),
        migrations.AddField(
            model_name='needylocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='place_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
