# Generated by Django 5.2.1 on 2025-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0005_rename_name_needylocation_sender_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needylocation',
            name='address',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/'),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='place_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='sender_name',
            field=models.CharField(max_length=150),
        ),
    ]
