# Generated by Django 5.2.1 on 2025-10-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0006_remove_needylocation_address_fooddonation_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='photo',
        ),
        migrations.AddField(
            model_name='needylocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='place_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='sender_name',
            field=models.CharField(max_length=100),
        ),
    ]
