# Generated by Django 5.2.1 on 2025-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0007_remove_fooddonation_photo_needylocation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/'),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
