# Generated by Django 5.2.1 on 2025-10-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0008_fooddonation_photo_alter_fooddonation_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
