# Generated by Django 5.2.1 on 2025-10-22 07:45

import Share_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share_App', '0009_fooddonation_donor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needylocation',
            name='address',
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='photo',
            field=models.ImageField(blank=True, default=Share_App.models.food_photo_default, null=True, upload_to='food_photos/'),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='photo',
            field=models.ImageField(blank=True, default=Share_App.models.location_photo_default, null=True, upload_to='location_photos/'),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='place_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='sender_name',
            field=models.CharField(max_length=200),
        ),
    ]
